language: perl

sudo: false

env:
  - PREREQS="Devel::Trepan B::DeparseTree Devel::Callsite"

after_failure:
  - cat /home/travis/.cpanm/work/*/build.log

install:
  # Prerequisites
  - cpanm LEONT/Module-Build-0.4224.tar.gz
  - perl ./Build.PL
  - AUTOMATED_TESTING=1 cpanm --installdeps --notest .
  - GIT2CL='./git2cl' make ChangeLog distmeta distcheck

perl:
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"
